app/routes/auth_routes.py
from flask import Blueprint, redirect, url_for, request, jsonify, flash, abort, render_template
from app.utils.db_utils import DatabaseUtil
from flask import current_app as app

auth = Blueprint('auth', __name__)

@auth.route('/api/users/login', methods=['GET', 'POST'])
def login_post():
    if request.method == "POST":
        username = request.form["username"]
        password = request.form["password"]
        email = None  # Initialize email variable

        # Check if the username is an email address
        if "@" in username:
            email = username
            username = None  # Set username to None if it's an email address
        databaseobj = DatabaseUtil()
        databaseobj.connect()
        user = databaseobj.get_user(username=username, email=email)
        if user:
            user_id = user["user_id"]
            if databaseobj.check_hashpasswd(user_id, password):
                app.config["CURRENT_USER"] = user_id
                databaseobj.close()
                return redirect(url_for('main.upload_page'))
        databaseobj.close()
        error = "Invalid email/username or password"
        return render_template('login.html', error=error )
    # jsonify({"message": "invalid username/email or password!"}), 400



@auth.route('/api/users/logout')
def logout():
    pass
    return 

@auth.route('/api/users/register', methods=['GET', 'POST'])
def register_post():
    if request.method == "POST":
        try:

            database = DatabaseUtil()
            database.connect()
            first_name = request.form["first_name"]
            last_name = request.form["last_name"]
            email = request.form["email_address"]
            password = request.form["password"]
            username = request.form["username"]
            user = {
            "firstName": first_name,
            "lastName": last_name,
            "email": email,
            "password": password,
            "username": username
            }
            database.create_user(user)
            database.close()
            return redirect(url_for('main.login_page'))
            # return jsonify({"message": "registration successful!"}), 200
        except Exception as e:
            return redirect(url_for('main.register'))

app/routes/main_routes.py
from flask import Blueprint, jsonify, request, render_template
from app.utils.db_utils import DatabaseUtil
from app.utils.image_utils import CompressImage

main = Blueprint('main', __name__)

@main.route('/')
@main.route('/index')
def index():
    return render_template('index.html')
@main.route('/login')
def login_page():
    return render_template('login.html')

@main.route('/download')
def download():
    return render_template('download.html')

@main.route('/register')
def register():
    return render_template('register.html')
@main.route('/profile')
def profile():
    return render_template('profile.html')
@main.route('/upload')
def upload_page():
    return render_template('upload.html')

app/templates/download.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>compressio | download</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='images/image.png') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/download.css') }}">
    <link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css'> 
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" />
</head>
<body>
    <nav class="nav">
        <a href="{{ url_for('main.index') }}" id="logo-container">
            <div class="logo">
                <img src="{{ url_for('static', filename='images/image.png') }}" alt="app-logo">
            </div>
        </a>
        <div class="nav-container">
            <ul>
                <li><a href="#" id="user-files">myfiles</a></li>
                <li><a href="{{ url_for('main.upload_page') }}">upload</a></li>
                <li><a href="{{ url_for('main.profile') }}">profile</a></li>
            </ul>
        </div>
    </nav>
    <div class="download-container">
   
    </div>
    <footer>
        <div class="footer-container">
            <div class="footer-quicklinks">
                <h2>Quick Links</h2>
                <p><a href="{{ url_for('main.index') }}">Home</a></p>
                <p><a href="">About Compressio</a></p>
                <p><a href="">Services</a></p>
                <p><a href="">Resources</a></p>
                <p><a href="">Contact Us</a></p>   
            </div>
            <div class="footer-help">
                <h2>Help & Support</h2>
                <p><a href="">Privacy Policy</a></p>
                <p><a href="">Terms & Conditions</a></p>
                <p><a href="">Cookie Notices</a></p>
                <p><a href="">Support Center</a></p>
            </div>
            <div class="footer-contacts">
                <h2>Contacts</h2>
                <p>
                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" class="mr-2 text-black iconify iconify--ph" width="1em" height="1em" viewBox="0 0 256 256" style="font-size: 20px;"><path fill="currentColor" d="m222.37 158.46l-47.11-21.11l-.13-.06a16 16 0 0 0-15.17 1.4a8 8 0 0 0-.75.56L134.87 160c-15.42-7.49-31.34-23.29-38.83-38.51l20.78-24.71c.2-.25.39-.5.57-.77a16 16 0 0 0 1.32-15.06v-.12L97.54 33.64a16 16 0 0 0-16.62-9.52A56.26 56.26 0 0 0 32 80c0 79.4 64.6 144 144 144a56.26 56.26 0 0 0 55.88-48.92a16 16 0 0 0-9.51-16.62M176 208A128.14 128.14 0 0 1 48 80a40.2 40.2 0 0 1 34.87-40a.6.6 0 0 0 0 .12l21 47l-20.67 24.74a6 6 0 0 0-.57.77a16 16 0 0 0-1 15.7c9.06 18.53 27.73 37.06 46.46 46.11a16 16 0 0 0 15.75-1.14a8 8 0 0 0 .74-.56L168.89 152l47 21.05h.11A40.21 40.21 0 0 1 176 208"></path></svg>
                    <span>+254-712345678</span>
                </p>
                <p>
                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" class="mr-2 text-black iconify iconify--mdi-light" width="1em" height="1em" viewBox="0 0 24 24" style="font-size: 20px;"><path fill="currentColor" d="M5 5h13a3 3 0 0 1 3 3v9a3 3 0 0 1-3 3H5a3 3 0 0 1-3-3V8a3 3 0 0 1 3-3m0 1c-.5 0-.94.17-1.28.47l7.78 5.03l7.78-5.03C18.94 6.17 18.5 6 18 6zm6.5 6.71L3.13 7.28C3.05 7.5 3 7.75 3 8v9a2 2 0 0 0 2 2h13a2 2 0 0 0 2-2V8c0-.25-.05-.5-.13-.72z"></path></svg>
                    <span>admin@compressio.tech</span>
                </p>
                <p>
                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" class="mr-2 text-black iconify iconify--system-uicons" width="1em" height="1em" viewBox="0 0 21 21" style="font-size: 20px;"><g fill="none" fill-rule="evenodd" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" transform="translate(4 2)"><path d="m6.5 16.54l.631-.711c.716-.82 1.36-1.598 1.933-2.338l.473-.624c1.975-2.661 2.963-4.773 2.963-6.334C12.5 3.201 9.814.5 6.5.5s-6 2.701-6 6.033c0 1.561.988 3.673 2.963 6.334l.473.624a54.84 54.84 0 0 0 2.564 3.05"></path><circle cx="6.5" cy="6.5" r="2.5"></circle></g></svg>
                    <span>1102 Applewood Adams, Ngong Road</span>
                </p>
            </div>
        </div>
        <span>
            <p>copyright &copy; 2024 Compressio Africa</p>
        </span>
    </footer>
    <script src="{{ url_for('static', filename='js/download.js') }}"></script>
</body>
</html>

app/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{{ url_for('static', filename='images/image.png') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}">
    <link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css'> 
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" />
    <title>compressio | login</title>
</head>
<body>
    <nav class="nav">
        <a href="{{ url_for('main.index') }}" id="logo-container">
            <div class="logo">
                <img src="{{ url_for('static', filename='images/image.png') }}" alt="app-logo">
            </div>
        </a>
        <div class="nav-container">
            <ul>
                <li><a href="{{ url_for('main.index') }}"> Home</a></li>
                <li><a href="{{ url_for('main.register') }}">Register</a></li>
            </ul>
        </div>
    </nav>
    <div class="login-form">
        <form action="{{ url_for('auth.login_post') }}" method="POST" class="login" id="loginForm">
            <span>
                <h2>Login using Compressio Account</h2>
            </span>
            <span>
                <input type="text" name="username" placeholder="username or email address" id="username">
            </span>
            <div><small id="username_msg"></small><i class="fa-solid fa-circle-check" id="usrnm_success_icon" style="color: #1bc52f;"></i><i class="fa-solid fa-circle-exclamation" id="usrnm_fail_icon" style="color: #f53505;"></i></div>
            <span>
                <div id="wrap-password"><input type="password" name="password" placeholder="password" id="password" >
                    <span class="password-reveal"><i class="fas fa-eye"></i></span></div>
            </span>
            <div><small id="password_msg"></small><i class="fa-solid fa-circle-check" id="passwd_success_icon" style="color: #1bc52f;"></i><i class="fa-solid fa-circle-exclamation" id="passwd_fail_icon" style="color: #f53505;"></i></div>
            <span>
                <button id="login-button" type="submit">Login</button>
            </span>
            <span>
                <p>Don't have an account? <a href="{{ url_for('main.register') }}">Sign up</a> forgot password? <a href="#">Reset</a></p>
            </span>
        </form>
    </div>
    <footer>
        <div class="footer-container">
            <div class="footer-quicklinks">
                <h2>Quick Links</h2>
                <p><a href="{{ url_for('main.index') }}">Home</a></p>
                <p><a href="">About Compressio</a></p>
                <p><a href="">Services</a></p>
                <p><a href="">Resources</a></p>
                <p><a href="">Contact Us</a></p>   
            </div>
            <div class="footer-help">
                <h2>Help & Support</h2>
                <p><a href="">Privacy Policy</a></p>
                <p><a href="">Terms & Conditions</a></p>
                <p><a href="">Cookie Notices</a></p>
                <p><a href="">Support Center</a></p>
            </div>
            <div class="footer-contacts">
                <h2>Contacts</h2>
                <p>
                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" class="mr-2 text-black iconify iconify--ph" width="1em" height="1em" viewBox="0 0 256 256" style="font-size: 20px;"><path fill="currentColor" d="m222.37 158.46l-47.11-21.11l-.13-.06a16 16 0 0 0-15.17 1.4a8 8 0 0 0-.75.56L134.87 160c-15.42-7.49-31.34-23.29-38.83-38.51l20.78-24.71c.2-.25.39-.5.57-.77a16 16 0 0 0 1.32-15.06v-.12L97.54 33.64a16 16 0 0 0-16.62-9.52A56.26 56.26 0 0 0 32 80c0 79.4 64.6 144 144 144a56.26 56.26 0 0 0 55.88-48.92a16 16 0 0 0-9.51-16.62M176 208A128.14 128.14 0 0 1 48 80a40.2 40.2 0 0 1 34.87-40a.6.6 0 0 0 0 .12l21 47l-20.67 24.74a6 6 0 0 0-.57.77a16 16 0 0 0-1 15.7c9.06 18.53 27.73 37.06 46.46 46.11a16 16 0 0 0 15.75-1.14a8 8 0 0 0 .74-.56L168.89 152l47 21.05h.11A40.21 40.21 0 0 1 176 208"></path></svg>
                    <span>+254-712345678</span>
                </p>
                <p>
                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" class="mr-2 text-black iconify iconify--mdi-light" width="1em" height="1em" viewBox="0 0 24 24" style="font-size: 20px;"><path fill="currentColor" d="M5 5h13a3 3 0 0 1 3 3v9a3 3 0 0 1-3 3H5a3 3 0 0 1-3-3V8a3 3 0 0 1 3-3m0 1c-.5 0-.94.17-1.28.47l7.78 5.03l7.78-5.03C18.94 6.17 18.5 6 18 6zm6.5 6.71L3.13 7.28C3.05 7.5 3 7.75 3 8v9a2 2 0 0 0 2 2h13a2 2 0 0 0 2-2V8c0-.25-.05-.5-.13-.72z"></path></svg>
                    <span>admin@compressio.tech</span>
                </p>
                <p>
                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" class="mr-2 text-black iconify iconify--system-uicons" width="1em" height="1em" viewBox="0 0 21 21" style="font-size: 20px;"><g fill="none" fill-rule="evenodd" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" transform="translate(4 2)"><path d="m6.5 16.54l.631-.711c.716-.82 1.36-1.598 1.933-2.338l.473-.624c1.975-2.661 2.963-4.773 2.963-6.334C12.5 3.201 9.814.5 6.5.5s-6 2.701-6 6.033c0 1.561.988 3.673 2.963 6.334l.473.624a54.84 54.84 0 0 0 2.564 3.05"></path><circle cx="6.5" cy="6.5" r="2.5"></circle></g></svg>
                    <span>1102 Applewood Adams, Ngong Road</span>
                </p>
            </div>
        </div>
        <span>
            <p>copyright &copy; 2024 Compressio Africa</p>
        </span>
    </footer>
    <script src="{{ url_for('static', filename='js/login.js') }}"></script>
</body>
</html>

app/templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{{ url_for('static', filename='images/image.png') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/profile.css') }}">
    <link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css'> 
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" />
    <title>compressio | profile</title>
</head>
<body>
    <nav class="nav">
        <a href="{{ url_for('main.index') }}" id="logo-container">
            <div class="logo">
                <img src="../static/images/image.png" alt="app-logo">
            </div>
        </a>
        <div class="nav-container">
            <ul>
                <li><a href="{{ url_for('main.index') }}"> Home</a></li>
                <li><a href="{{ url_for('main.download') }}">myfiles</a></li>
                <li><a href="{{ url_for('main.upload_page') }}">upload</a></li>
            </ul>
        </div>
    </nav>
    <div class="profile-container">
        
    </div>
    <footer>
        <div class="footer-container">
            <div class="footer-quicklinks">
                <h2>Quick Links</h2>
                <p><a href="{{ url_for('main.index') }}">Home</a></p>
                <p><a href="">About Compressio</a></p>
                <p><a href="">Services</a></p>
                <p><a href="">Resources</a></p>
                <p><a href="">Contact Us</a></p>   
            </div>
            <div class="footer-help">
                <h2>Help & Support</h2>
                <p><a href="">Privacy Policy</a></p>
                <p><a href="">Terms & Conditions</a></p>
                <p><a href="">Cookie Notices</a></p>
                <p><a href="">Support Center</a></p>
            </div>
            <div class="footer-contacts">
                <h2>Contacts</h2>
                <p>
                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" class="mr-2 text-black iconify iconify--ph" width="1em" height="1em" viewBox="0 0 256 256" style="font-size: 20px;"><path fill="currentColor" d="m222.37 158.46l-47.11-21.11l-.13-.06a16 16 0 0 0-15.17 1.4a8 8 0 0 0-.75.56L134.87 160c-15.42-7.49-31.34-23.29-38.83-38.51l20.78-24.71c.2-.25.39-.5.57-.77a16 16 0 0 0 1.32-15.06v-.12L97.54 33.64a16 16 0 0 0-16.62-9.52A56.26 56.26 0 0 0 32 80c0 79.4 64.6 144 144 144a56.26 56.26 0 0 0 55.88-48.92a16 16 0 0 0-9.51-16.62M176 208A128.14 128.14 0 0 1 48 80a40.2 40.2 0 0 1 34.87-40a.6.6 0 0 0 0 .12l21 47l-20.67 24.74a6 6 0 0 0-.57.77a16 16 0 0 0-1 15.7c9.06 18.53 27.73 37.06 46.46 46.11a16 16 0 0 0 15.75-1.14a8 8 0 0 0 .74-.56L168.89 152l47 21.05h.11A40.21 40.21 0 0 1 176 208"></path></svg>
                    <span>+254-712345678</span>
                </p>
                <p>
                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" class="mr-2 text-black iconify iconify--mdi-light" width="1em" height="1em" viewBox="0 0 24 24" style="font-size: 20px;"><path fill="currentColor" d="M5 5h13a3 3 0 0 1 3 3v9a3 3 0 0 1-3 3H5a3 3 0 0 1-3-3V8a3 3 0 0 1 3-3m0 1c-.5 0-.94.17-1.28.47l7.78 5.03l7.78-5.03C18.94 6.17 18.5 6 18 6zm6.5 6.71L3.13 7.28C3.05 7.5 3 7.75 3 8v9a2 2 0 0 0 2 2h13a2 2 0 0 0 2-2V8c0-.25-.05-.5-.13-.72z"></path></svg>
                    <span>admin@compressio.tech</span>
                </p>
                <p>
                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" class="mr-2 text-black iconify iconify--system-uicons" width="1em" height="1em" viewBox="0 0 21 21" style="font-size: 20px;"><g fill="none" fill-rule="evenodd" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" transform="translate(4 2)"><path d="m6.5 16.54l.631-.711c.716-.82 1.36-1.598 1.933-2.338l.473-.624c1.975-2.661 2.963-4.773 2.963-6.334C12.5 3.201 9.814.5 6.5.5s-6 2.701-6 6.033c0 1.561.988 3.673 2.963 6.334l.473.624a54.84 54.84 0 0 0 2.564 3.05"></path><circle cx="6.5" cy="6.5" r="2.5"></circle></g></svg>
                    <span>1102 Applewood Adams, Ngong Road</span>
                </p>
            </div>
        </div>
        <span>
            <p>copyright &copy; 2024 Compressio Africa</p>
        </span>
    </footer>
    <script src="../static/js/login.js"></script>
</body>
</html>

app/templates/upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>compressio | upload</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='images/image.png') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/upload.css') }}">
    <link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css'> 
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" />
</head>
<body>
    <nav class="nav">
        <a href="{{ url_for('main.index') }}" id="logo-container">
            <div class="logo">
                <img src="{{ url_for('static', filename='images/image.png') }}" alt="app-logo">
            </div>
        </a>
        <div class="nav-container">
            <ul>
                <li><a href="{{ url_for('main.index') }}"> Home</a></li>
                <li><a href="{{ url_for('main.download') }}">myfiles</a></li>
                <li><a href="{{ url_for('main.profile') }}">profile</a></li>
            </ul>
        </div>
    </nav>
    <div class="container-image-form">
        <div class="upload-box">
                <P>Drag & drop images jpeg, png, gif, webp to upload and compress</P>
                <form method="POST" enctype="multipart/form-data" id="image-form">
                    <input type="file" id="image" name="image" accept=".jpeg, .jpg, .png, .webp, .gif" value="upload images" multiple>
                    <label for="image" id="image-input"><i class="fa-solid fa-cloud-arrow-up fa-4x" style="color: #36454f;"></i></label>
                    <input type="submit" value="Upload Image" name="submit-button" id="submit-button">
                </form>
        </div>
        <div id="image-list">

        </div>

    </div>
    <footer>
        <div class="footer-container">
            <div class="footer-quicklinks">
                <h2>Quick Links</h2>
                <p><a href="{{ url_for('main.index') }}">Home</a></p>
                <p><a href="">About Compressio</a></p>
                <p><a href="">Services</a></p>
                <p><a href="">Resources</a></p>
                <p><a href="">Contact Us</a></p>   
            </div>
            <div class="footer-help">
                <h2>Help & Support</h2>
                <p><a href="">Privacy Policy</a></p>
                <p><a href="">Terms & Conditions</a></p>
                <p><a href="">Cookie Notices</a></p>
                <p><a href="">Support Center</a></p>
            </div>
            <div class="footer-contacts">
                <h2>Contacts</h2>
                <p>
                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" class="mr-2 text-black iconify iconify--ph" width="1em" height="1em" viewBox="0 0 256 256" style="font-size: 20px;"><path fill="currentColor" d="m222.37 158.46l-47.11-21.11l-.13-.06a16 16 0 0 0-15.17 1.4a8 8 0 0 0-.75.56L134.87 160c-15.42-7.49-31.34-23.29-38.83-38.51l20.78-24.71c.2-.25.39-.5.57-.77a16 16 0 0 0 1.32-15.06v-.12L97.54 33.64a16 16 0 0 0-16.62-9.52A56.26 56.26 0 0 0 32 80c0 79.4 64.6 144 144 144a56.26 56.26 0 0 0 55.88-48.92a16 16 0 0 0-9.51-16.62M176 208A128.14 128.14 0 0 1 48 80a40.2 40.2 0 0 1 34.87-40a.6.6 0 0 0 0 .12l21 47l-20.67 24.74a6 6 0 0 0-.57.77a16 16 0 0 0-1 15.7c9.06 18.53 27.73 37.06 46.46 46.11a16 16 0 0 0 15.75-1.14a8 8 0 0 0 .74-.56L168.89 152l47 21.05h.11A40.21 40.21 0 0 1 176 208"></path></svg>
                    <span>+254-712345678</span>
                </p>
                <p>
                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" class="mr-2 text-black iconify iconify--mdi-light" width="1em" height="1em" viewBox="0 0 24 24" style="font-size: 20px;"><path fill="currentColor" d="M5 5h13a3 3 0 0 1 3 3v9a3 3 0 0 1-3 3H5a3 3 0 0 1-3-3V8a3 3 0 0 1 3-3m0 1c-.5 0-.94.17-1.28.47l7.78 5.03l7.78-5.03C18.94 6.17 18.5 6 18 6zm6.5 6.71L3.13 7.28C3.05 7.5 3 7.75 3 8v9a2 2 0 0 0 2 2h13a2 2 0 0 0 2-2V8c0-.25-.05-.5-.13-.72z"></path></svg>
                    <span>admin@compressio.tech</span>
                </p>
                <p>
                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" class="mr-2 text-black iconify iconify--system-uicons" width="1em" height="1em" viewBox="0 0 21 21" style="font-size: 20px;"><g fill="none" fill-rule="evenodd" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" transform="translate(4 2)"><path d="m6.5 16.54l.631-.711c.716-.82 1.36-1.598 1.933-2.338l.473-.624c1.975-2.661 2.963-4.773 2.963-6.334C12.5 3.201 9.814.5 6.5.5s-6 2.701-6 6.033c0 1.561.988 3.673 2.963 6.334l.473.624a54.84 54.84 0 0 0 2.564 3.05"></path><circle cx="6.5" cy="6.5" r="2.5"></circle></g></svg>
                    <span>1102 Applewood Adams, Ngong Road</span>
                </p>
            </div>
        </div>
        <span>
            <p>copyright &copy; 2024 Compressio Africa</p>
        </span>
    </footer>
    <script src="{{ url_for('static', filename='js/upload.js') }}"></script>
</body>
</html>